### ISSUE TITLE
zmiana z JSON na GSON

### ISSUE THREAD

**Issue by deestt** [Rollczi/minecraft-lista-plugin#1]

**Comment by Rollczi** [comment]
Jaki jest cel tej zmiany?

**Comment by deestt** [comment]
chodzi o to ze mniej bedzie blibloteka wazyla bo gson jest odrazu w bukkitcie

**Comment by Rollczi** [comment]
gson jest na 1.8.8? nie obracam się w tym temacie

**Comment by Kamilkime** [comment]
Tak, plugin VIshopu normalnie używa gsona, tylko wymusza chyba kompatybilność ze starszą wersją dla pewności

**Comment by deestt** [comment]
zobaczylem ze jest w bukkitcie 1.8 json simple wiec mozna zrobic compileOnly gsona + jsonsimple

**Comment by deestt** [comment]
a nie przepraszam jest na 1.8 gson
